name: Build and Deploy

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install azd
      uses: Azure/setup-azd@v0.1.0

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: azd auth login
      run: |
        AZURE_CREDENTIALS=$(echo "$AZURE_CREDENTIALS" | jq -r '.')
        AZURE_CLIENT_ID=$(echo "$AZURE_CREDENTIALS" | jq -r '.clientId')
        AZURE_TENANT_ID=$(echo "$AZURE_CREDENTIALS" | jq -r '.tenantId')
        AZURE_CLIENT_SECRET=$(echo "$AZURE_CREDENTIALS" | jq -r '.clientSecret')
        
        azd version

        azd auth login `
          --client-id $AZURE_CLIENT_ID `
          --client-secret $AZURE_CLIENT_SECRET `
          --tenant-id $AZURE_TENANT_ID
        
        azd show

